## STAGE 1
FROM node:12.7-alpine as build
WORKDIR /usr/src/app
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build

## STAGE 2
FROM nginx:1.17.1-alpine
COPY --from=build /usr/src/app/dist/mock-ui /usr/share/nginx/html


